### ISSUE TITLE
Get rid of old_ems_id

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#196]
Archiving used to clear `ems_id` and store it in `old_ems_id`.
`old_ems_id` is unnecessary now that we retain `ems_id` (since https://github.com/ManageIQ/manageiq/pull/15251 and related PRs).

- [x] backfill unset `ems_id` from `old_ems_id` — https://github.com/ManageIQ/manageiq-schema/pull/18 already did that.
- [x] drop any code checking `old_ems_id` / `old_ext_management_system`.
  - [x] #267 Stop checking in plugins/manageiq-providers-kubernetes/app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/capture_context_mixin.rb
  - [x] Stop checking in app/models/metric/ci_mixin/capture.rb #17695
  - [x] remove and stop including app/models/mixins/old_ems_mixin.rb  #17695
  - [x] Stop checking in app/models/chargeback_container_image.rb, app/models/chargeback_container_project.rb #17695
- [x] delete the column.  :fire: :dragon: https://github.com/ManageIQ/manageiq-schema/pull/593

Then there is also `old_container_project_id` in ContainerGroup, not sure if that's obsolete, out of scope here.

**Comment by cben** [comment]
@miq-bot add-label technical debt

**Comment by cben** [comment]
@miq-bot remove-label stale

**Comment by agrare** [comment]
Marking this as `pinned` since we really should finish this out
