### ISSUE TITLE
Containers graph refresh

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#27]
A tracking issue for things to do (in all repos).
https://github.com/ManageIQ/manageiq/pull/14337 PoC is now nearly :100: % conversion but a lot of work remains.
This issue is for **full refresh**; targeted is out of scope => tracking separately in #114.

- [x] :pray: @zakiva's effort to add deletion tests https://github.com/ManageIQ/manageiq-providers-openshift/pull/18.
- [x] :pray: Improve refresher test coverage, there are some things uncovered even by straightforward refresh from scratch.
  - [x] I have a couple commits in https://github.com/ManageIQ/manageiq/pull/14337 adding tests.
    => extracted to ManageIQ/manageiq-providers-openshift#19
  - [x] SecurityContext has no tests
  - [x] PVC are not in cassette => they are in the deletions cassete #74
  - [ ] Project labels have no tests?
  - [x] 🐛 possibly found bug in linking pod -> build pod didn't look up by namespace (Erez fixing)
  - [x] some untested things left unimplemented (variables starting with `_`) in #52 ?
- [ ] :lipstick: Consider some renames for consistency in refresh parser e.g. `s/:project/:container_project/`. 
 These would avoid some special casing in both save_inventory and refresh save.  (I've tried to keep TODOs in the POC pr.)
- [x] :building_construction: Rebase post repo split, find place to stick new code.
  - [x] k8s refactoring #46
  - [x] k8s implement graph refresh #30, #52
  - [x] openshift refactoring https://github.com/ManageIQ/manageiq-providers-openshift/pull/30
  - [x] openshift implement graph refresh https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/57, https://github.com/ManageIQ/manageiq-providers-openshift/pull/34
  - [x] Upgrade existing refresher from deprected `parse_legacy_inventory` to newer collect/parse separation.
- [x] :building_construction: Don't replace save_inventory_container, add a setting to toggle.
  - [x] Unhide setting.
  - [x] enable by default! #112, https://github.com/ManageIQ/manageiq-providers-openshift/pull/48
- [x] :building_construction: Implement disconnections (currently just deletes).  Can set `:delete_method` but needs batching to be fast.
  - [x] Enable Zahi's deletion tests for graph refresh too.
- [x] :building_construction: :horse_racing: Persister #73, https://github.com/ManageIQ/manageiq-providers-openshift/pull/39
  - [x] setting for batched saver strategy 
- [x] :building_construction: :bug: #126 Implement label->tag mapping (currently not saving tags).
  - Tests skipped for now.
- [x] Measure performance / memory ⏱ 📝 

above list is surely incomplete.

RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1470021

**Comment by cben** [comment]
Extracted some tests https://github.com/ManageIQ/manageiq-providers-openshift/pull/19 ,
associations https://github.com/ManageIQ/manageiq/pull/15298

Adam nicely refactored & rebased much of the other changes into https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/30, plan is to finish and land that (behind a flag), then do similarly for openshift.

**Comment by cben** [comment]
- [ ] component statuses tries to store a KubeClient object `   :message=>#<Kubeclient::ComponentStatus health="true">,`
- [ ] fixing some volume-related bugs, adding tests

**Comment by cben** [comment]
- [ ] secondary index by blacklisted `:namespace` is bad — seems to work for full refresh but can't match records from DB, as those don't have `namespace`, only `container_project_id`.

**Comment by cben** [comment]
- [ ] ContainerImage creation event has no tests

**Comment by cben** [comment]
- [ ] `cross_link_node` is done during parsing, consider batched

**Comment by cben** [comment]
- [ ] there is tricky bug with `save_unused_images: false` mode deleting existing child custom_attributes records.  Fix known (thanks Ladislav).
  - [x] https://github.com/ManageIQ/manageiq/pull/15903
  - [ ] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/106
  - [ ] https://github.com/ManageIQ/manageiq-providers-openshift/pull/46

We might need more extensive deletion tests for other entities...

**Comment by moolitayer** [comment]
@cben are we keeping a list of known issue somewhere? Label Tag Mapping is all I could find (except for the `save_unused_images` issue that has it's own prs)

**Comment by cben** [comment]
Yes, this is the list :-)

Added emojis to categorize (approximately) correctness/unimplemeted :building_construction: / bugs :bug:  / desired tests :pray: / performance :racehorse: / code polish :lipstick:.

Tag mapping (I'm working on it) and unused images are the only current known bugs.

**Comment by cben** [comment]
This is long done.
