### ISSUE TITLE
Multiple managers for Kubernetes

### ISSUE THREAD

**Issue by moolitayer** [ManageIQ/manageiq-providers-kubernetes#39]
### WAT ?
- Monitoring = Metrics & Alerts
- Container providers should have a main manager `ContainerManager` and a secondary manager `MonitoringManager` linked by parant_manager_id. 
- All monitoring workers should move under the `MonitoringManager`
- There should be two possible implementations for the Monitoring Manager living side by side. Hawkular and Prometheus. The implementation should be different files.

### WHY ?
Move closer to other providers where separate entities in the provider are separate managers. Better worker management. Examples:
- If the hawkular authentication status is bad, we should stop the related workers: metrics(currently).
- We are adding a new event listener from hawkular alerts on top of the kubernetes event listener. That would belong under the Monitoring manager.

### HOW ?
(In merge order)
- [x] Add monitoring manager [manageiq/#15354](https://github.com/ManageIQ/manageiq/pull/15354)
- [x] Add kubernetes monitoring manager [manageiq-providers-kubernetes/#38](https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/38)
- [x] Add openshift monitoring manager [manageiq-providers-openshift/#21](https://github.com/ManageIQ/manageiq-providers-openshift/pull/21)
- [x] Adapt manageiq to new managers [manageiq/15506](https://github.com/ManageIQ/manageiq/pull/15506)
- [ ] Add prometheus event collection for Kubernetes under the new manager [manageiq-providers-kubernetes/#40](https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/40)
- [ ] Same for OepnShift [manageiq-providers-openshift/#22](https://github.com/ManageIQ/manageiq-providers-openshift/pull/22)
- [ ] Switch existing monitoring workers (hawkular metrics collector) to use the new manager
- [ ] Add a new event catcher
- [ ] Make the kubernetes monitor have two implementations: one for hawkular and one for prometheus (in separate files)

#### prometheus related work
https://github.com/ManageIQ/manageiq/pull/15473
https://github.com/ManageIQ/manageiq-ui-classic/pull/1640

**Comment by cben** [comment]
1. Does this involve upgrading k8s and openshift from being managers (EMS)
to Providers?
Or will there be some sibling manager -> manager link?

2. Will the metrics Endpoints eventually move into the monitoring manager?
IOW how will API look? (not opposed to changing, just curious)

**Comment by moolitayer** [comment]
> 1. Does this involve upgrading k8s and openshift from being managers (EMS)
> to Providers?
> Or will there be some sibling manager -> manager link?

Turns out both these approaches exist in ManageIQ[1][2][3]. After consultation with @blomquisg and @Ladas these route seems more productive for us.



> 2. Will the metrics Endpoints eventually move into the monitoring manager?
> IOW how will API look? (not opposed to changing, just curious)

Don't know yet. I will probably start by taking a look at what other providers are doing.

**Comment by blomquisg** [comment]
It's worth pointing out that we're discussing the Provider/Manager relationship: http://talk.manageiq.org/t/rethinking-providers-and-managers/2494

I'm not sure exactly all the overlaps with this yet.  But, I'm sure there's going to be some overlaps.

Also, the notion of controlling workers via Managers will hopefully be a thing of the past as we dive more and more in the ReArch ("H" Release).

/cc @Fryguy @gtanzillo, @agrare, @durandom

**Comment by agrare** [comment]
Kubernetes has a monitoring manager now so I'm going to say this is done.  Please reopen and update the description if you want to do more here.
